/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MKV
 */
public class Display extends javax.swing.JFrame {

    Main mf;
    
    public Display(Main mf) {
        initComponents();
        this.mf=mf;
        mammal_cb.setVisible(false);
        bird_cb.setVisible(false);
        reptile_cb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allanimal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        all_rb = new javax.swing.JRadioButton();
        custom_rb = new javax.swing.JRadioButton();
        mammal_cb = new javax.swing.JCheckBox();
        reptile_cb = new javax.swing.JCheckBox();
        bird_cb = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        allanimal.add(all_rb);
        all_rb.setText("All");
        all_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_rbActionPerformed(evt);
            }
        });

        allanimal.add(custom_rb);
        custom_rb.setText("Custom");
        custom_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_rbActionPerformed(evt);
            }
        });

        mammal_cb.setText("Mammal");
        mammal_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mammal_cbActionPerformed(evt);
            }
        });

        reptile_cb.setText("Reptile");
        reptile_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reptile_cbActionPerformed(evt);
            }
        });

        bird_cb.setText("Bird");
        bird_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bird_cbActionPerformed(evt);
            }
        });

        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(all_rb)
                    .addComponent(custom_rb)
                    .addComponent(mammal_cb)
                    .addComponent(reptile_cb)
                    .addComponent(bird_cb)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(all_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custom_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mammal_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reptile_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bird_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mammal_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mammal_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mammal_cbActionPerformed

    private void reptile_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reptile_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reptile_cbActionPerformed

    private void bird_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bird_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bird_cbActionPerformed

    private void all_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_rbActionPerformed
        if(all_rb.isSelected()){
            mammal_cb.setVisible(false);
            bird_cb.setVisible(false);
            reptile_cb.setVisible(false);
            textarea.setText("");
        }
    }//GEN-LAST:event_all_rbActionPerformed

    private void custom_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_rbActionPerformed
       if(custom_rb.isSelected()){
           mammal_cb.setVisible(true);
           bird_cb.setVisible(true);
           reptile_cb.setVisible(true);
           textarea.setText("");
       }
    }//GEN-LAST:event_custom_rbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str="";
        textarea.setText("");
        if(all_rb.isSelected()){
            textarea.setText(AnimalSys.displayWithString());
        }
        else if(custom_rb.isSelected()){
            
            for(Animal a: AnimalSys.getAnimals())
            {
                if(mammal_cb.isSelected())
                {
                    if(a instanceof Mammal)
                        str+=a.toString();
                }
                if(reptile_cb.isSelected())
                {
                    if(a instanceof Reptile)
                        str+=a.toString();
                }
                if(bird_cb.isSelected())
                {
                    if(a instanceof Bird)
                        str+=a.toString();
                }
            }
            textarea.setText(str);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       mf.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all_rb;
    private javax.swing.ButtonGroup allanimal;
    private javax.swing.JCheckBox bird_cb;
    private javax.swing.JRadioButton custom_rb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mammal_cb;
    private javax.swing.JCheckBox reptile_cb;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
